Repository doctrine/data-fixtures, pull requests merged in 2023-12, with the labels that each got.

#455 Add parameter types
  src/AbstractFixture.php
  src/Executor/AbstractExecutor.php
  src/Executor/MongoDBExecutor.php
  src/Executor/MultipleTransactionORMExecutor.php
  src/Executor/ORMExecutor.php
  src/Executor/PHPCRExecutor.php
  src/Loader.php
  src/ProxyReferenceRepository.php
  src/Purger/ORMPurger.php
  src/ReferenceRepository.php
  src/Sorter/TopologicalSorter.php
Labels: Improvement

#456 Reference classes using current namespace in `@see` phpdoc
  src/AbstractFixture.php
  src/Sorter/Vertex.php
Labels: Documentation

#457 Make Executor and Purger classes final
  UPGRADE.md
  docs/en/explanation/transactions-and-purging.rst
  src/Executor/AbstractExecutor.php
  src/Executor/MongoDBExecutor.php
  src/Executor/ORMExecutor.php
  src/Executor/PHPCRExecutor.php
  src/Purger/MongoDBPurger.php
  src/Purger/ORMPurger.php
  src/Purger/PHPCRPurger.php
Labels: Deprecation

#460 Bump Doctrine workflows
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#461 Drop support for PHP 7
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  phpcs.xml.dist
  phpstan-baseline.neon
  psalm-baseline.xml
  src/AbstractFixture.php
  src/Event/Listener/MongoDBReferenceListener.php
  src/Event/Listener/ORMReferenceListener.php
  src/Executor/AbstractExecutor.php
  src/Executor/MongoDBExecutor.php
  src/Executor/ORMExecutorCommon.php
  src/Executor/PHPCRExecutor.php
  src/Loader.php
  src/ProxyReferenceRepository.php
  src/Purger/MongoDBPurger.php
  src/Purger/ORMPurger.php
  src/Purger/PHPCRPurger.php
  src/ReferenceRepository.php
  tests/Common/DataFixtures/Purger/MongoDBPurgerTest.php
  tests/Common/DataFixtures/Purger/ORMPurgerExcludeTest.php
  tests/Common/DataFixtures/TestDocument/Role.php
  tests/Common/DataFixtures/TestEntity/Group.php
  tests/Common/DataFixtures/TestEntity/GroupWithSchema.php
  tests/Common/DataFixtures/TestEntity/Link.php
  tests/Common/DataFixtures/TestEntity/Quoted.php
  tests/Common/DataFixtures/TestEntity/Role.php
  tests/Common/DataFixtures/TestEntity/User.php
  tests/Common/DataFixtures/TestEntity/UserWithSchema.php
  tests/Common/DataFixtures/TestFixtures/RoleFixture.php
  tests/Common/DataFixtures/TestPurgeEntity/ExcludedEntity.php
  tests/Common/DataFixtures/TestPurgeEntity/IncludedEntity.php
  tests/Common/DataFixtures/TestTypes/UuidType.php
  tests/Common/DataFixtures/TestValueObjects/Uuid.php
  tests/Mock/ForwardCompatibleEntityManager.php
  tests/Mock/Node.php
Labels: Improvement

#463 Backport tests for strict return types
  tests/Common/DataFixtures/Executor/ORMExecutorTest.php
  tests/Common/DataFixtures/ReferenceRepositoryTest.php
Labels: Test Suite
