Repository doctrine/data-fixtures, pull requests merged in 2023-04, with the labels that each got.

#439 Bump workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#438 Modernize codebase for PHP 7.4
  .github/workflows/continuous-integration.yml
  composer.json
  phpcs.xml.dist
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  src/AbstractFixture.php
  src/Event/Listener/MongoDBReferenceListener.php
  src/Event/Listener/ORMReferenceListener.php
  src/Executor/AbstractExecutor.php
  src/Executor/MongoDBExecutor.php
  src/Executor/MultipleTransactionORMExecutor.php
  src/Executor/ORMExecutorCommon.php
  src/Executor/PHPCRExecutor.php
  src/Loader.php
  src/ProxyReferenceRepository.php
  src/Purger/MongoDBPurger.php
  src/Purger/ORMPurger.php
  src/Purger/PHPCRPurger.php
  src/ReferenceRepository.php
  src/Sorter/TopologicalSorter.php
  src/Sorter/Vertex.php
  tests/Common/DataFixtures/BaseTestCase.php
  tests/Common/DataFixtures/Executor/PHPCRExecutorTest.php
  tests/Common/DataFixtures/FixtureTest.php
  tests/Common/DataFixtures/LoaderTest.php
  tests/Common/DataFixtures/ProxyReferenceRepositoryTest.php
  tests/Common/DataFixtures/Purger/MongoDBPurgerTest.php
  tests/Common/DataFixtures/Purger/ORMPurgerExcludeTest.php
  tests/Common/DataFixtures/ReferenceRepositoryTest.php
  tests/Common/DataFixtures/TestDocument/Role.php
  tests/Common/DataFixtures/TestEntity/Group.php
  tests/Common/DataFixtures/TestEntity/GroupWithSchema.php
  tests/Common/DataFixtures/TestEntity/Link.php
  tests/Common/DataFixtures/TestEntity/Quoted.php
  tests/Common/DataFixtures/TestEntity/Role.php
  tests/Common/DataFixtures/TestEntity/User.php
  tests/Common/DataFixtures/TestEntity/UserWithSchema.php
  tests/Common/DataFixtures/TestFixtures/RoleFixture.php
  tests/Common/DataFixtures/TestPurgeEntity/ExcludedEntity.php
  tests/Common/DataFixtures/TestPurgeEntity/IncludedEntity.php
  tests/Common/DataFixtures/TestTypes/UuidType.php
  tests/Common/DataFixtures/TestValueObjects/Uuid.php
Labels: Improvement

#411 Speedup ORMPurger
  src/Purger/ORMPurger.php
Labels: Improvement

#441 Added test showing the issue when fixture depends on ordered fixture
  src/Loader.php
  tests/Common/DataFixtures/DependentFixtureTest.php
Labels: Bug
