Repository doctrine/data-fixtures, pull requests merged in 2024-11, with the labels that each got.

#492 Ensure 2.0.x is deprecation-free
  composer.json
  tests/Common/DataFixtures/Executor/AbstractExecutorTest.php
Labels: Test Suite

#491 Ensure the codebase is totally typed
  UPGRADE.md
  phpcs.xml.dist
  src/AbstractFixture.php
  src/Executor/AbstractExecutor.php
  src/Purger/ORMPurger.php
  src/ReferenceRepository.php
Labels: BC break

#493 Drop Psalm in favor of just PHPStan
  .gitattributes
  .github/workflows/static-analysis.yml
  composer.json
  psalm-baseline.xml
  psalm.xml
  src/AbstractFixture.php
  src/DependentFixtureInterface.php
  src/Loader.php
  src/ReferenceRepository.php
  src/Sorter/Vertex.php
Labels: CI

#497 [v2] Convert `@final` to hard `final`
  UPGRADE.md
  phpcs.xml.dist
  phpstan-baseline.neon
  src/Executor/MongoDBExecutor.php
  src/Executor/ORMExecutor.php
  src/Executor/PHPCRExecutor.php
  src/Purger/MongoDBPurger.php
  src/Purger/MongoDBPurgerInterface.php
  src/Purger/ORMPurger.php
  src/Purger/ORMPurgerInterface.php
  src/Purger/PHPCRPurger.php
  src/Purger/PHPCRPurgerInterface.php
  tests/Common/DataFixtures/Executor/ORMExecutorSharedFixtureTest.php
  tests/Common/DataFixtures/Executor/ORMExecutorTest.php
  tests/Common/DataFixtures/Executor/PHPCRExecutorTest.php
Labels: BC break
