Repository doctrine/data-fixtures, pull requests merged in 2024-03, with the labels that each got.

#465 Add tests about new reference usage
  tests/Common/DataFixtures/Executor/ORMExecutorSharedFixtureTest.php
  tests/Common/DataFixtures/ProxyReferenceRepositoryTest.php
  tests/Common/DataFixtures/ReferenceRepositoryTest.php
  tests/Common/DataFixtures/TestFixtures/UserFixture.php
Labels: Test Suite

#467 Adjust PHPStan settings for ORM 3
  phpstan.neon.dist
Labels: Static Analysis

#462 Deprecate callable loggers
  UPGRADE.md
  composer.json
  src/Executor/AbstractExecutor.php
  tests/Common/DataFixtures/Executor/AbstractExecutorTest.php
Labels: Improvement, Deprecation

#471 Remove callable loggers
  UPGRADE.md
  composer.json
  src/Executor/AbstractExecutor.php
  tests/Common/DataFixtures/Executor/AbstractExecutorTest.php
Labels: BC break

#469 Remove usage of Doctrine annotations
  composer.json
  phpstan.neon.dist
  tests/Common/DataFixtures/BaseTestCase.php
  tests/Common/DataFixtures/Purger/MongoDBPurgerTest.php
  tests/Common/DataFixtures/TestDocument/Role.php
  tests/Common/DataFixtures/TestEntity/Group.php
  tests/Common/DataFixtures/TestEntity/GroupWithSchema.php
  tests/Common/DataFixtures/TestEntity/Link.php
  tests/Common/DataFixtures/TestEntity/Quoted.php
  tests/Common/DataFixtures/TestEntity/Role.php
  tests/Common/DataFixtures/TestEntity/User.php
  tests/Common/DataFixtures/TestEntity/UserWithSchema.php
  tests/Common/DataFixtures/TestPurgeEntity/ExcludedEntity.php
  tests/Common/DataFixtures/TestPurgeEntity/IncludedEntity.php
Labels: Test Suite

#459 Add return types on public classes and interfaces
  UPGRADE.md
  phpcs.xml.dist
  psalm-baseline.xml
  src/AbstractFixture.php
  src/DependentFixtureInterface.php
  src/Executor/AbstractExecutor.php
  src/Executor/MongoDBExecutor.php
  src/Executor/ORMExecutor.php
  src/Executor/ORMExecutorCommon.php
  src/Executor/PHPCRExecutor.php
  src/FixtureInterface.php
  src/Loader.php
  src/OrderedFixtureInterface.php
  src/ProxyReferenceRepository.php
  src/Purger/MongoDBPurger.php
  src/Purger/ORMPurger.php
  src/Purger/ORMPurgerInterface.php
  src/Purger/PHPCRPurger.php
  src/Purger/PurgerInterface.php
  src/ReferenceRepository.php
  src/SharedFixtureInterface.php
  src/Sorter/TopologicalSorter.php
Labels: BC break
